// Realisaties: echte modellen, anoniem (geen klant- of werfnamen).
// Elk beeld in een lichte én donkere versie (scripts/renders-maken.mjs).

import type { Locale } from "@/lib/i18n/config";

export type Categorie = "wegenis" | "grondwerk" | "bouwput" | "terrein";
type Tekst = { titel: string; tekst: string };

// Machinebesturingen per realisatie (merknamen, geen submodellen). Toewijzing
// van Vincent (2/10): evenwichtig, soms 1, soms 2, soms 3 systemen per model.
// Geen stelsel of land per project (anoniem). De algemene zin op /realisaties
// zegt dat elk model voor alle systemen geleverd kan worden.
export type Systeem = "Trimble" | "Topcon" | "Leica" | "Unicontrol" | "CHCNAV" | "Komatsu" | "Caterpillar";

// Schermlezerlabel voor de rij systeem-chips.
export const SYSTEMEN_LABEL: Record<Locale, string> = {
  nl: "Machinebesturing",
  fr: "Guidage d'engins",
  en: "Machine control",
  de: "Maschinensteuerung",
  es: "Control de maquinaria",
};

export type Realisatie = {
  id: string;
  licht: string;
  donker: string;
  cat: Categorie;
  systemen: Systeem[];
  nl: Tekst;
  fr: Tekst;
  en: Tekst;
  de: Tekst;
  es: Tekst;
};

const r = (id: string) => ({ licht: `/3d/r/${id}-licht.webp`, donker: `/3d/r/${id}-donker.webp` });

export const CATEGORIEEN: Record<Categorie, Record<Locale, string>> = {
  wegenis: { nl: "Wegenis", fr: "Voiries", en: "Roads", de: "Straßenbau", es: "Viales" },
  grondwerk: { nl: "Grondwerk & platformen", fr: "Terrassements & plateformes", en: "Earthworks & platforms", de: "Erdbau & Planien", es: "Movimiento de tierras y plataformas" },
  bouwput: { nl: "Bouwputten & bekkens", fr: "Fouilles & bassins", en: "Excavations & basins", de: "Baugruben & Becken", es: "Excavaciones y balsas" },
  terrein: { nl: "Terreinmodellen", fr: "Modèles de terrain", en: "Terrain models", de: "Geländemodelle", es: "Modelos de terreno" },
};

// Vaste aanvulling voor alt-teksten: wat er op elk beeld te zien is.
export const BEELD_ALT: Record<Locale, string> = {
  nl: "3D-model voor machinesturing",
  fr: "modèle 3D pour le guidage d'engins",
  en: "3D model for machine control",
  de: "3D-Modell für Maschinensteuerung",
  es: "modelo 3D para control de maquinaria",
};

export const REALISATIES: Realisatie[] = [
  { id: "t029", ...r("t029"), cat: "wegenis", systemen: ["Trimble", "Topcon"],
    nl: { titel: "Aftakking", tekst: "Wegaansluiting met vloeiende bochten en verkanting." },
    fr: { titel: "Embranchement", tekst: "Raccord routier avec courbes fluides et dévers." },
    en: { titel: "Junction", tekst: "Road tie-in with smooth curves and crossfall." },
    de: { titel: "Abzweigung", tekst: "Straßenanschluss mit fließenden Kurven und Querneigung." },
    es: { titel: "Bifurcación", tekst: "Enlace viario con curvas suaves y peralte." } },
  { id: "kruispunt", licht: "/3d/weg-kruispunt-licht.png", donker: "/3d/weg-kruispunt-donker.png", cat: "wegenis", systemen: ["Topcon", "Leica", "Unicontrol"],
    nl: { titel: "Weg met kruispunt", tekst: "Lang tracé met aansluiting, in hoogtekleuren." },
    fr: { titel: "Route avec carrefour", tekst: "Long tracé avec raccord, en couleurs hypsométriques." },
    en: { titel: "Road with junction", tekst: "Long alignment with tie-in, in height colours." },
    de: { titel: "Straße mit Kreuzung", tekst: "Lange Trasse mit Anschluss, in Höhenfarben." },
    es: { titel: "Carretera con cruce", tekst: "Trazado largo con enlace, en colores hipsométricos." } },
  { id: "t003", ...r("t003"), cat: "wegenis", systemen: ["Trimble"],
    nl: { titel: "Wegennet verkaveling", tekst: "Interne wegen met kruispunten en keerpunt." },
    fr: { titel: "Voiries de lotissement", tekst: "Voiries internes avec carrefours et aire de retournement." },
    en: { titel: "Housing estate roads", tekst: "Internal roads with junctions and turning head." },
    de: { titel: "Erschließungsstraßen Baugebiet", tekst: "Interne Straßen mit Kreuzungen und Wendeanlage." },
    es: { titel: "Viales de urbanización", tekst: "Viales interiores con cruces y fondo de saco." } },
  { id: "t021", ...r("t021"), cat: "wegenis", systemen: ["Topcon", "Komatsu"],
    nl: { titel: "Weg in ophoging", tekst: "Rijweg met taluds aan beide zijden." },
    fr: { titel: "Route en remblai", tekst: "Chaussée avec talus des deux côtés." },
    en: { titel: "Road on embankment", tekst: "Carriageway with slopes on both sides." },
    de: { titel: "Straße auf Damm", tekst: "Fahrbahn mit Böschungen auf beiden Seiten." },
    es: { titel: "Carretera en terraplén", tekst: "Calzada con taludes a ambos lados." } },
  { id: "t035", ...r("t035"), cat: "wegenis", systemen: ["Leica"],
    nl: { titel: "Slingerend tracé", tekst: "Pad met opeenvolgende bochten en aansluiting." },
    fr: { titel: "Tracé sinueux", tekst: "Chemin avec courbes successives et raccord." },
    en: { titel: "Winding alignment", tekst: "Path with successive bends and a tie-in." },
    de: { titel: "Kurvige Trasse", tekst: "Weg mit aufeinanderfolgenden Kurven und Anschluss." },
    es: { titel: "Trazado sinuoso", tekst: "Camino con curvas sucesivas y enlace." } },
  { id: "t002", ...r("t002"), cat: "wegenis", systemen: ["Trimble", "Unicontrol"],
    nl: { titel: "Toerit en keerlus", tekst: "Hellende toerit met keerlus en verhardingen." },
    fr: { titel: "Rampe et boucle", tekst: "Rampe d'accès avec boucle de retournement." },
    en: { titel: "Ramp and loop", tekst: "Sloping access ramp with turning loop." },
    de: { titel: "Rampe und Wendeschleife", tekst: "Geneigte Zufahrtsrampe mit Wendeschleife und Befestigungen." },
    es: { titel: "Rampa y lazo", tekst: "Rampa de acceso en pendiente con lazo de giro y pavimentos." } },
  { id: "t040", ...r("t040"), cat: "wegenis", systemen: ["CHCNAV"],
    nl: { titel: "Ontsluitingsweg", tekst: "Weg rond een terrein, met hoogteverloop." },
    fr: { titel: "Voie de desserte", tekst: "Route autour d'un terrain, avec profil en long." },
    en: { titel: "Access road", tekst: "Road around a site, with longitudinal profile." },
    de: { titel: "Erschließungsstraße", tekst: "Straße um ein Gelände, mit Längsprofil." },
    es: { titel: "Vial de acceso", tekst: "Vial alrededor de una parcela, con perfil longitudinal." } },
  { id: "trace", licht: "/3d/weg-trace-licht.png", donker: "/3d/weg-trace-donker.png", cat: "wegenis", systemen: ["Trimble", "Topcon", "Leica"],
    nl: { titel: "Lang wegtracé", tekst: "Tracé over honderden meters, met profielen." },
    fr: { titel: "Long tracé routier", tekst: "Tracé sur des centaines de mètres, avec profils." },
    en: { titel: "Long road alignment", tekst: "Alignment over hundreds of metres, with profiles." },
    de: { titel: "Lange Straßentrasse", tekst: "Trasse über Hunderte Meter, mit Profilen." },
    es: { titel: "Trazado de carretera largo", tekst: "Trazado de cientos de metros, con perfiles." } },

  { id: "t088", ...r("t088"), cat: "grondwerk", systemen: ["Topcon"],
    nl: { titel: "Bedrijfsterrein", tekst: "Platformen en verhardingen op verschillende niveaus." },
    fr: { titel: "Zone d'activité", tekst: "Plateformes et revêtements à plusieurs niveaux." },
    en: { titel: "Industrial site", tekst: "Platforms and paving at different levels." },
    de: { titel: "Gewerbegebiet", tekst: "Planien und Befestigungen auf verschiedenen Höhen." },
    es: { titel: "Polígono industrial", tekst: "Plataformas y pavimentos a distintas cotas." } },
  { id: "t014", ...r("t014"), cat: "grondwerk", systemen: ["Trimble", "Caterpillar"],
    nl: { titel: "Platform met funderingsputten", tekst: "Werkvlak met tientallen putten op eigen diepte." },
    fr: { titel: "Plateforme avec puits de fondation", tekst: "Plateforme avec des dizaines de puits à leur propre profondeur." },
    en: { titel: "Platform with foundation pits", tekst: "Working platform with dozens of pits, each at its own depth." },
    de: { titel: "Planum mit Fundamentgruben", tekst: "Arbeitsplanum mit Dutzenden Gruben, jede auf ihrer eigenen Tiefe." },
    es: { titel: "Plataforma con pozos de cimentación", tekst: "Plataforma de trabajo con decenas de pozos, cada uno a su propia profundidad." } },
  { id: "t008", ...r("t008"), cat: "grondwerk", systemen: ["Unicontrol"],
    nl: { titel: "Platform met sleuven", tekst: "Kruisende funderingssleuven in een platform." },
    fr: { titel: "Plateforme avec tranchées", tekst: "Tranchées de fondation croisées dans une plateforme." },
    en: { titel: "Platform with trenches", tekst: "Crossing foundation trenches in a platform." },
    de: { titel: "Planum mit Gräben", tekst: "Sich kreuzende Fundamentgräben in einem Planum." },
    es: { titel: "Plataforma con zanjas", tekst: "Zanjas de cimentación que se cruzan en una plataforma." } },
  { id: "t019", ...r("t019"), cat: "grondwerk", systemen: ["Topcon", "CHCNAV"],
    nl: { titel: "Getrapt platform", tekst: "Werkvlakken op meerdere niveaus." },
    fr: { titel: "Plateforme en gradins", tekst: "Plateformes sur plusieurs niveaux." },
    en: { titel: "Stepped platform", tekst: "Working surfaces on several levels." },
    de: { titel: "Abgetrepptes Planum", tekst: "Arbeitsflächen auf mehreren Höhen." },
    es: { titel: "Plataforma escalonada", tekst: "Superficies de trabajo a varias cotas." } },
  { id: "t067", ...r("t067"), cat: "grondwerk", systemen: ["Trimble", "Leica", "Unicontrol"],
    nl: { titel: "Raster van funderingsblokken", tekst: "Regelmatig raster, elk blok op niveau." },
    fr: { titel: "Trame de massifs", tekst: "Trame régulière, chaque massif à niveau." },
    en: { titel: "Grid of foundation blocks", tekst: "Regular grid, every block at level." },
    de: { titel: "Raster von Einzelfundamenten", tekst: "Regelmäßiges Raster, jedes Fundament auf Höhe." },
    es: { titel: "Retícula de zapatas", tekst: "Retícula regular, cada zapata a cota." } },
  { id: "t095", ...r("t095"), cat: "grondwerk", systemen: ["Komatsu"],
    nl: { titel: "Platformen op niveaus", tekst: "Aansluitende vlakken met overgangstaluds." },
    fr: { titel: "Plateformes à niveaux", tekst: "Surfaces contiguës avec talus de transition." },
    en: { titel: "Platforms at levels", tekst: "Adjoining surfaces with transition slopes." },
    de: { titel: "Planien auf mehreren Höhen", tekst: "Angrenzende Flächen mit Übergangsböschungen." },
    es: { titel: "Plataformas a varias cotas", tekst: "Superficies contiguas con taludes de transición." } },
  { id: "t033", ...r("t033"), cat: "grondwerk", systemen: ["Trimble"],
    nl: { titel: "Talud in bocht", tekst: "Gebogen talud met constante helling." },
    fr: { titel: "Talus en courbe", tekst: "Talus courbe à pente constante." },
    en: { titel: "Curved embankment", tekst: "Curved slope at a constant gradient." },
    de: { titel: "Böschung in der Kurve", tekst: "Gekrümmte Böschung mit konstanter Neigung." },
    es: { titel: "Talud en curva", tekst: "Talud curvo con pendiente constante." } },
  { id: "grondwerk", licht: "/3d/relief-grondwerk-licht.png", donker: "/3d/relief-grondwerk-donker.png", cat: "grondwerk", systemen: ["Topcon", "Leica"],
    nl: { titel: "Grondwerk", tekst: "Platformen in reliëf, met hoogtekleuren." },
    fr: { titel: "Terrassement", tekst: "Plateformes en relief, en couleurs hypsométriques." },
    en: { titel: "Earthworks", tekst: "Platforms in relief, in height colours." },
    de: { titel: "Erdbau", tekst: "Planien im Relief, in Höhenfarben." },
    es: { titel: "Movimiento de tierras", tekst: "Plataformas en relieve, en colores hipsométricos." } },

  { id: "bouwput", licht: "/3d/relief-bouwput-licht.png", donker: "/3d/relief-bouwput-donker.png", cat: "bouwput", systemen: ["Trimble", "Topcon", "Caterpillar"],
    nl: { titel: "Bouwput", tekst: "Uitgraving met taluds en werkvloer op niveau." },
    fr: { titel: "Fouille", tekst: "Excavation avec talus et fond de fouille à niveau." },
    en: { titel: "Excavation", tekst: "Pit with embankments and formation level." },
    de: { titel: "Baugrube", tekst: "Aushub mit Böschungen und Sohle auf Höhe." },
    es: { titel: "Excavación", tekst: "Vaciado con taludes y fondo de excavación a cota." } },
  { id: "t037", ...r("t037"), cat: "bouwput", systemen: ["Unicontrol"],
    nl: { titel: "Bouwput met taluds", tekst: "Diepe uitgraving met taluds rondom." },
    fr: { titel: "Fouille talutée", tekst: "Excavation profonde avec talus périphériques." },
    en: { titel: "Battered excavation", tekst: "Deep excavation with slopes all round." },
    de: { titel: "Geböschte Baugrube", tekst: "Tiefer Aushub mit umlaufenden Böschungen." },
    es: { titel: "Excavación ataluzada", tekst: "Excavación profunda con taludes en todo el perímetro." } },
  { id: "t015", ...r("t015"), cat: "bouwput", systemen: ["Trimble", "Topcon"],
    nl: { titel: "Bouwkuip", tekst: "Complexe kuip met verschillende diepten." },
    fr: { titel: "Fouille complexe", tekst: "Fouille avec différentes profondeurs." },
    en: { titel: "Complex pit", tekst: "Pit with several depths." },
    de: { titel: "Komplexe Baugrube", tekst: "Baugrube mit unterschiedlichen Tiefen." },
    es: { titel: "Excavación compleja", tekst: "Excavación con distintas profundidades." } },
  { id: "t077", ...r("t077"), cat: "bouwput", systemen: ["Leica", "CHCNAV"],
    nl: { titel: "Uitgraving met werkvloer", tekst: "Werkvloer en randen op de juiste hoogte." },
    fr: { titel: "Fouille avec fond", tekst: "Fond et bords à la bonne hauteur." },
    en: { titel: "Excavation with formation", tekst: "Formation and edges at the right height." },
    de: { titel: "Aushub mit Sohle", tekst: "Sohle und Ränder auf der richtigen Höhe." },
    es: { titel: "Excavación con fondo", tekst: "Fondo y bordes a la cota correcta." } },
  { id: "t018", ...r("t018"), cat: "bouwput", systemen: ["Topcon"],
    nl: { titel: "Wachtbekken", tekst: "Bekken met taluds en vlakke bodem." },
    fr: { titel: "Bassin d'orage", tekst: "Bassin avec talus et fond plat." },
    en: { titel: "Retention basin", tekst: "Basin with slopes and a level bottom." },
    de: { titel: "Regenrückhaltebecken", tekst: "Becken mit Böschungen und ebener Sohle." },
    es: { titel: "Balsa de retención", tekst: "Balsa con taludes y fondo plano." } },
  { id: "t074", ...r("t074"), cat: "bouwput", systemen: ["Trimble"],
    nl: { titel: "Kuip", tekst: "Vierkante uitgraving met constante taluds." },
    fr: { titel: "Cuvette", tekst: "Excavation carrée à talus constants." },
    en: { titel: "Square pit", tekst: "Square excavation with constant slopes." },
    de: { titel: "Quadratische Grube", tekst: "Quadratischer Aushub mit konstanten Böschungen." },
    es: { titel: "Fosa cuadrada", tekst: "Excavación cuadrada con taludes constantes." } },
  { id: "t017", ...r("t017"), cat: "bouwput", systemen: ["Trimble", "Caterpillar"],
    nl: { titel: "Bekken met compartimenten", tekst: "Bekken met tussenwanden op niveau." },
    fr: { titel: "Bassin compartimenté", tekst: "Bassin avec cloisons à niveau." },
    en: { titel: "Compartmented basin", tekst: "Basin with divider walls at level." },
    de: { titel: "Becken mit Kammern", tekst: "Becken mit Trennwänden auf Höhe." },
    es: { titel: "Balsa compartimentada", tekst: "Balsa con muros divisorios a cota." } },
  { id: "sport", licht: "/3d/relief-sportterrein-licht.png", donker: "/3d/relief-sportterrein-donker.png", cat: "bouwput", systemen: ["Unicontrol", "Leica"],
    nl: { titel: "Sportterrein", tekst: "Vlak speelveld met afwatering naar de randen." },
    fr: { titel: "Terrain de sport", tekst: "Aire de jeu plane avec écoulement vers les bords." },
    en: { titel: "Sports field", tekst: "Level pitch draining to the edges." },
    de: { titel: "Sportplatz", tekst: "Ebenes Spielfeld mit Entwässerung zu den Rändern." },
    es: { titel: "Campo deportivo", tekst: "Terreno de juego plano con desagüe hacia los bordes." } },

  { id: "t013", ...r("t013"), cat: "terrein", systemen: ["Trimble", "Topcon", "CHCNAV"],
    nl: { titel: "Bestaand terrein", tekst: "Opgemeten maaiveld als basis voor het ontwerp." },
    fr: { titel: "Terrain existant", tekst: "Terrain naturel levé, base du projet." },
    en: { titel: "Existing ground", tekst: "Surveyed ground as the basis for the design." },
    de: { titel: "Bestehendes Gelände", tekst: "Vermessene Geländeoberfläche als Grundlage für den Entwurf." },
    es: { titel: "Terreno existente", tekst: "Terreno natural levantado como base del proyecto." } },
  { id: "t023", ...r("t023"), cat: "terrein", systemen: ["Topcon"],
    nl: { titel: "Terreinmodel", tekst: "Golvend terrein met fijne hoogtelijnen." },
    fr: { titel: "Modèle de terrain", tekst: "Terrain ondulé avec courbes fines." },
    en: { titel: "Terrain model", tekst: "Undulating ground with fine contours." },
    de: { titel: "Geländemodell", tekst: "Welliges Gelände mit feinen Höhenlinien." },
    es: { titel: "Modelo de terreno", tekst: "Terreno ondulado con curvas de nivel finas." } },
  { id: "hoogtelijnen", licht: "/3d/terrein-hoogtelijnen-licht.png", donker: "/3d/terrein-hoogtelijnen-donker.png", cat: "terrein", systemen: ["Trimble", "Leica"],
    nl: { titel: "Terrein op inplantingsplan", tekst: "Hoogtelijnen en lijnwerk over het plan." },
    fr: { titel: "Terrain sur plan d'implantation", tekst: "Courbes et filaire sur le plan." },
    en: { titel: "Site on layout plan", tekst: "Contours and linework over the plan." },
    de: { titel: "Gelände auf Lageplan", tekst: "Höhenlinien und Linien über dem Plan." },
    es: { titel: "Terreno sobre plano de implantación", tekst: "Curvas de nivel y líneas sobre el plano." } },
  { id: "t047", ...r("t047"), cat: "terrein", systemen: ["Topcon", "Komatsu"],
    nl: { titel: "Ophoging", tekst: "Organisch gevormde ophoging met verloop." },
    fr: { titel: "Remblai", tekst: "Remblai de forme organique." },
    en: { titel: "Fill area", tekst: "Organically shaped fill." },
    de: { titel: "Aufschüttung", tekst: "Organisch geformte Aufschüttung mit Verlauf." },
    es: { titel: "Relleno", tekst: "Relleno de forma orgánica." } },
  { id: "t054", ...r("t054"), cat: "terrein", systemen: ["CHCNAV"],
    nl: { titel: "Terrein met verdiepingen", tekst: "Lokale laagtes en ophogingen in één model." },
    fr: { titel: "Terrain avec cuvettes", tekst: "Creux et remblais locaux dans un seul modèle." },
    en: { titel: "Ground with hollows", tekst: "Local hollows and fills in one model." },
    de: { titel: "Gelände mit Senken", tekst: "Lokale Senken und Aufschüttungen in einem Modell." },
    es: { titel: "Terreno con depresiones", tekst: "Depresiones y rellenos locales en un solo modelo." } },
  { id: "t081", ...r("t081"), cat: "terrein", systemen: ["Trimble", "Topcon", "Unicontrol"],
    nl: { titel: "Hellend terrein", tekst: "Groot hoogteverschil, helder in kleur." },
    fr: { titel: "Terrain en pente", tekst: "Fort dénivelé, lisible en couleurs." },
    en: { titel: "Sloping ground", tekst: "Large height difference, clear in colour." },
    de: { titel: "Hanggelände", tekst: "Großer Höhenunterschied, klar in Farbe." },
    es: { titel: "Terreno en pendiente", tekst: "Gran desnivel, claro en colores." } },
  { id: "tin", licht: "/3d/driehoeksnet-licht.png", donker: "/3d/driehoeksnet-donker.png", cat: "terrein", systemen: ["Leica"],
    nl: { titel: "Driehoeksnet (TIN)", tekst: "Het oppervlak waarop de machine stuurt." },
    fr: { titel: "Réseau de triangles (TIN)", tekst: "La surface sur laquelle la machine se guide." },
    en: { titel: "Triangle network (TIN)", tekst: "The surface the machine guides on." },
    de: { titel: "Dreiecksnetz (TIN)", tekst: "Die Oberfläche, an der die Maschine steuert." },
    es: { titel: "Red de triángulos (TIN)", tekst: "La superficie sobre la que se guía la máquina." } },
  { id: "lijnwerk", ...r("p-lijnwerk-draad"), cat: "terrein", systemen: ["Trimble", "Topcon"],
    nl: { titel: "Lijnwerk", tekst: "Breeklijnen en kanten als referentie voor de machinist." },
    fr: { titel: "Filaire", tekst: "Lignes de rupture et bords comme repères pour le conducteur." },
    en: { titel: "Linework", tekst: "Breaklines and edges as references for the operator." },
    de: { titel: "Linien", tekst: "Bruchkanten und Kanten als Referenz für den Maschinenführer." },
    es: { titel: "Líneas", tekst: "Líneas de ruptura y bordes como referencia para el operador." } },
];

// Uitgelicht: één model in vier weergaven.
export type Weergave = "hoogte" | "helling" | "hoogtelijn" | "draad";
export const WEERGAVEN: Record<Weergave, Record<Locale, string>> = {
  hoogte: { nl: "Hoogtekleuren", fr: "Couleurs hypsométriques", en: "Height colours", de: "Höhenfarben", es: "Colores hipsométricos" },
  helling: { nl: "Helling", fr: "Pente", en: "Slope", de: "Neigung", es: "Pendiente" },
  hoogtelijn: { nl: "Hoogtelijnen", fr: "Courbes de niveau", en: "Contours", de: "Höhenlinien", es: "Curvas de nivel" },
  draad: { nl: "Driehoeksnet", fr: "Réseau de triangles", en: "Triangle network", de: "Dreiecksnetz", es: "Red de triángulos" },
};

export const UITGELICHT: { id: string; systemen: Systeem[]; nl: Tekst; fr: Tekst; en: Tekst; de: Tekst; es: Tekst }[] = [
  { id: "platform", systemen: ["Trimble", "Topcon", "Leica"],
    nl: { titel: "Platform met funderingsstroken", tekst: "Een groot werkvlak met een raster van funderingsstroken, elk op zijn eigen niveau. De hellingskaart toont meteen of elke strook correct afwatert." },
    fr: { titel: "Plateforme avec semelles", tekst: "Une grande plateforme avec une trame de semelles, chacune à son propre niveau. La carte des pentes montre aussitôt si chaque semelle s'écoule correctement." },
    en: { titel: "Platform with strip foundations", tekst: "A large working platform with a grid of strip foundations, each at its own level. The slope map shows straight away whether every strip drains correctly." },
    de: { titel: "Planum mit Streifenfundamenten", tekst: "Ein großes Arbeitsplanum mit einem Raster von Streifenfundamenten, jedes auf seiner eigenen Höhe. Die Neigungskarte zeigt sofort, ob jeder Streifen korrekt entwässert." },
    es: { titel: "Plataforma con zapatas corridas", tekst: "Una gran plataforma de trabajo con una retícula de zapatas corridas, cada una a su propia cota. El mapa de pendientes muestra de inmediato si cada zapata desagua correctamente." } },
  { id: "uitgraving", systemen: ["Unicontrol", "Caterpillar"],
    nl: { titel: "Uitgraving met taluds", tekst: "Een uitgraving met taluds rondom en een vlakke bodem. In het driehoeksnet ziet u hoe het oppervlak opgebouwd is waarop de machine stuurt." },
    fr: { titel: "Excavation talutée", tekst: "Une excavation avec talus périphériques et fond plat. Le réseau de triangles montre comment est construite la surface sur laquelle la machine se guide." },
    en: { titel: "Battered excavation", tekst: "An excavation with slopes all round and a level bottom. The triangle network shows how the surface the machine guides on is built." },
    de: { titel: "Geböschter Aushub", tekst: "Ein Aushub mit umlaufenden Böschungen und ebener Sohle. Im Dreiecksnetz sehen Sie, wie die Oberfläche aufgebaut ist, an der die Maschine steuert." },
    es: { titel: "Excavación ataluzada", tekst: "Una excavación con taludes en todo el perímetro y fondo plano. La red de triángulos muestra cómo está construida la superficie sobre la que se guía la máquina." } },
];
