// Realisaties: echte modellen, anoniem (geen klant- of werfnamen).
// Elk beeld in een lichte én donkere versie (scripts/renders-maken.mjs).

export type Categorie = "wegenis" | "grondwerk" | "bouwput" | "terrein";
type Tekst = { titel: string; tekst: string };
export type Realisatie = {
  id: string;
  licht: string;
  donker: string;
  cat: Categorie;
  nl: Tekst;
  fr: Tekst;
  en: Tekst;
};

const r = (id: string) => ({ licht: `/3d/r/${id}-licht.webp`, donker: `/3d/r/${id}-donker.webp` });

export const CATEGORIEEN: Record<Categorie, { nl: string; fr: string; en: string }> = {
  wegenis: { nl: "Wegenis", fr: "Voiries", en: "Roads" },
  grondwerk: { nl: "Grondwerk & platformen", fr: "Terrassements & plateformes", en: "Earthworks & platforms" },
  bouwput: { nl: "Bouwputten & bekkens", fr: "Fouilles & bassins", en: "Excavations & basins" },
  terrein: { nl: "Terreinmodellen", fr: "Modèles de terrain", en: "Terrain models" },
};

export const REALISATIES: Realisatie[] = [
  { id: "t029", ...r("t029"), cat: "wegenis",
    nl: { titel: "Aftakking", tekst: "Wegaansluiting met vloeiende bochten en verkanting." },
    fr: { titel: "Embranchement", tekst: "Raccord routier avec courbes fluides et dévers." },
    en: { titel: "Junction", tekst: "Road tie-in with smooth curves and crossfall." } },
  { id: "kruispunt", licht: "/3d/weg-kruispunt-licht.png", donker: "/3d/weg-kruispunt-donker.png", cat: "wegenis",
    nl: { titel: "Weg met kruispunt", tekst: "Lang tracé met aansluiting, in hoogtekleuren." },
    fr: { titel: "Route avec carrefour", tekst: "Long tracé avec raccord, en couleurs hypsométriques." },
    en: { titel: "Road with junction", tekst: "Long alignment with tie-in, in height colours." } },
  { id: "t003", ...r("t003"), cat: "wegenis",
    nl: { titel: "Wegennet verkaveling", tekst: "Interne wegen met kruispunten en keerpunt." },
    fr: { titel: "Voiries de lotissement", tekst: "Voiries internes avec carrefours et aire de retournement." },
    en: { titel: "Housing estate roads", tekst: "Internal roads with junctions and turning head." } },
  { id: "t021", ...r("t021"), cat: "wegenis",
    nl: { titel: "Weg in ophoging", tekst: "Rijweg met taluds aan beide zijden." },
    fr: { titel: "Route en remblai", tekst: "Chaussée avec talus des deux côtés." },
    en: { titel: "Road on embankment", tekst: "Carriageway with slopes on both sides." } },
  { id: "t035", ...r("t035"), cat: "wegenis",
    nl: { titel: "Slingerend tracé", tekst: "Pad met opeenvolgende bochten en aansluiting." },
    fr: { titel: "Tracé sinueux", tekst: "Chemin avec courbes successives et raccord." },
    en: { titel: "Winding alignment", tekst: "Path with successive bends and a tie-in." } },
  { id: "t002", ...r("t002"), cat: "wegenis",
    nl: { titel: "Toerit en keerlus", tekst: "Hellende toerit met keerlus en verhardingen." },
    fr: { titel: "Rampe et boucle", tekst: "Rampe d'accès avec boucle de retournement." },
    en: { titel: "Ramp and loop", tekst: "Sloping access ramp with turning loop." } },
  { id: "t040", ...r("t040"), cat: "wegenis",
    nl: { titel: "Ontsluitingsweg", tekst: "Weg rond een terrein, met hoogteverloop." },
    fr: { titel: "Voie de desserte", tekst: "Route autour d'un terrain, avec profil en long." },
    en: { titel: "Access road", tekst: "Road around a site, with longitudinal profile." } },
  { id: "trace", licht: "/3d/weg-trace-licht.png", donker: "/3d/weg-trace-donker.png", cat: "wegenis",
    nl: { titel: "Lang wegtracé", tekst: "Tracé over honderden meters, met profielen." },
    fr: { titel: "Long tracé routier", tekst: "Tracé sur des centaines de mètres, avec profils." },
    en: { titel: "Long road alignment", tekst: "Alignment over hundreds of metres, with profiles." } },

  { id: "t088", ...r("t088"), cat: "grondwerk",
    nl: { titel: "Bedrijfsterrein", tekst: "Platformen en verhardingen op verschillende niveaus." },
    fr: { titel: "Zone d'activité", tekst: "Plateformes et revêtements à plusieurs niveaux." },
    en: { titel: "Industrial site", tekst: "Platforms and paving at different levels." } },
  { id: "t014", ...r("t014"), cat: "grondwerk",
    nl: { titel: "Platform met funderingsputten", tekst: "Werkvlak met tientallen putten op eigen diepte." },
    fr: { titel: "Plateforme avec puits de fondation", tekst: "Plateforme avec des dizaines de puits à leur propre profondeur." },
    en: { titel: "Platform with foundation pits", tekst: "Working platform with dozens of pits, each at its own depth." } },
  { id: "t008", ...r("t008"), cat: "grondwerk",
    nl: { titel: "Platform met sleuven", tekst: "Kruisende funderingssleuven in een platform." },
    fr: { titel: "Plateforme avec tranchées", tekst: "Tranchées de fondation croisées dans une plateforme." },
    en: { titel: "Platform with trenches", tekst: "Crossing foundation trenches in a platform." } },
  { id: "t019", ...r("t019"), cat: "grondwerk",
    nl: { titel: "Getrapt platform", tekst: "Werkvlakken op meerdere niveaus." },
    fr: { titel: "Plateforme en gradins", tekst: "Plateformes sur plusieurs niveaux." },
    en: { titel: "Stepped platform", tekst: "Working surfaces on several levels." } },
  { id: "t067", ...r("t067"), cat: "grondwerk",
    nl: { titel: "Raster van funderingsblokken", tekst: "Regelmatig raster, elk blok op niveau." },
    fr: { titel: "Trame de massifs", tekst: "Trame régulière, chaque massif à niveau." },
    en: { titel: "Grid of foundation blocks", tekst: "Regular grid, every block at level." } },
  { id: "t095", ...r("t095"), cat: "grondwerk",
    nl: { titel: "Platformen op niveaus", tekst: "Aansluitende vlakken met overgangstaluds." },
    fr: { titel: "Plateformes à niveaux", tekst: "Surfaces contiguës avec talus de transition." },
    en: { titel: "Platforms at levels", tekst: "Adjoining surfaces with transition slopes." } },
  { id: "t033", ...r("t033"), cat: "grondwerk",
    nl: { titel: "Talud in bocht", tekst: "Gebogen talud met constante helling." },
    fr: { titel: "Talus en courbe", tekst: "Talus courbe à pente constante." },
    en: { titel: "Curved embankment", tekst: "Curved slope at a constant gradient." } },
  { id: "grondwerk", licht: "/3d/relief-grondwerk-licht.png", donker: "/3d/relief-grondwerk-donker.png", cat: "grondwerk",
    nl: { titel: "Grondwerk", tekst: "Platformen in reliëf, met hoogtekleuren." },
    fr: { titel: "Terrassement", tekst: "Plateformes en relief, en couleurs hypsométriques." },
    en: { titel: "Earthworks", tekst: "Platforms in relief, in height colours." } },

  { id: "bouwput", licht: "/3d/relief-bouwput-licht.png", donker: "/3d/relief-bouwput-donker.png", cat: "bouwput",
    nl: { titel: "Bouwput", tekst: "Uitgraving met taluds en werkvloer op niveau." },
    fr: { titel: "Fouille", tekst: "Excavation avec talus et fond de fouille à niveau." },
    en: { titel: "Excavation", tekst: "Pit with embankments and formation level." } },
  { id: "t037", ...r("t037"), cat: "bouwput",
    nl: { titel: "Bouwput met taluds", tekst: "Diepe uitgraving met taluds rondom." },
    fr: { titel: "Fouille talutée", tekst: "Excavation profonde avec talus périphériques." },
    en: { titel: "Battered excavation", tekst: "Deep excavation with slopes all round." } },
  { id: "t015", ...r("t015"), cat: "bouwput",
    nl: { titel: "Bouwkuip", tekst: "Complexe kuip met verschillende diepten." },
    fr: { titel: "Fouille complexe", tekst: "Fouille avec différentes profondeurs." },
    en: { titel: "Complex pit", tekst: "Pit with several depths." } },
  { id: "t077", ...r("t077"), cat: "bouwput",
    nl: { titel: "Uitgraving met werkvloer", tekst: "Werkvloer en randen op de juiste hoogte." },
    fr: { titel: "Fouille avec fond", tekst: "Fond et bords à la bonne hauteur." },
    en: { titel: "Excavation with formation", tekst: "Formation and edges at the right height." } },
  { id: "t018", ...r("t018"), cat: "bouwput",
    nl: { titel: "Wachtbekken", tekst: "Bekken met taluds en vlakke bodem." },
    fr: { titel: "Bassin d'orage", tekst: "Bassin avec talus et fond plat." },
    en: { titel: "Retention basin", tekst: "Basin with slopes and a level bottom." } },
  { id: "t074", ...r("t074"), cat: "bouwput",
    nl: { titel: "Kuip", tekst: "Vierkante uitgraving met constante taluds." },
    fr: { titel: "Cuvette", tekst: "Excavation carrée à talus constants." },
    en: { titel: "Square pit", tekst: "Square excavation with constant slopes." } },
  { id: "t017", ...r("t017"), cat: "bouwput",
    nl: { titel: "Bekken met compartimenten", tekst: "Bekken met tussenwanden op niveau." },
    fr: { titel: "Bassin compartimenté", tekst: "Bassin avec cloisons à niveau." },
    en: { titel: "Compartmented basin", tekst: "Basin with divider walls at level." } },
  { id: "sport", licht: "/3d/relief-sportterrein-licht.png", donker: "/3d/relief-sportterrein-donker.png", cat: "bouwput",
    nl: { titel: "Sportterrein", tekst: "Vlak speelveld met afwatering naar de randen." },
    fr: { titel: "Terrain de sport", tekst: "Aire de jeu plane avec écoulement vers les bords." },
    en: { titel: "Sports field", tekst: "Level pitch draining to the edges." } },

  { id: "t013", ...r("t013"), cat: "terrein",
    nl: { titel: "Bestaand terrein", tekst: "Opgemeten maaiveld als basis voor het ontwerp." },
    fr: { titel: "Terrain existant", tekst: "Terrain naturel levé, base du projet." },
    en: { titel: "Existing ground", tekst: "Surveyed ground as the basis for the design." } },
  { id: "t023", ...r("t023"), cat: "terrein",
    nl: { titel: "Terreinmodel", tekst: "Golvend terrein met fijne hoogtelijnen." },
    fr: { titel: "Modèle de terrain", tekst: "Terrain ondulé avec courbes fines." },
    en: { titel: "Terrain model", tekst: "Undulating ground with fine contours." } },
  { id: "hoogtelijnen", licht: "/3d/terrein-hoogtelijnen-licht.png", donker: "/3d/terrein-hoogtelijnen-donker.png", cat: "terrein",
    nl: { titel: "Terrein op inplantingsplan", tekst: "Hoogtelijnen en lijnwerk over het plan." },
    fr: { titel: "Terrain sur plan d'implantation", tekst: "Courbes et filaire sur le plan." },
    en: { titel: "Site on layout plan", tekst: "Contours and linework over the plan." } },
  { id: "t047", ...r("t047"), cat: "terrein",
    nl: { titel: "Ophoging", tekst: "Organisch gevormde ophoging met verloop." },
    fr: { titel: "Remblai", tekst: "Remblai de forme organique." },
    en: { titel: "Fill area", tekst: "Organically shaped fill." } },
  { id: "t054", ...r("t054"), cat: "terrein",
    nl: { titel: "Terrein met verdiepingen", tekst: "Lokale laagtes en ophogingen in één model." },
    fr: { titel: "Terrain avec cuvettes", tekst: "Creux et remblais locaux dans un seul modèle." },
    en: { titel: "Ground with hollows", tekst: "Local hollows and fills in one model." } },
  { id: "t081", ...r("t081"), cat: "terrein",
    nl: { titel: "Hellend terrein", tekst: "Groot hoogteverschil, helder in kleur." },
    fr: { titel: "Terrain en pente", tekst: "Fort dénivelé, lisible en couleurs." },
    en: { titel: "Sloping ground", tekst: "Large height difference, clear in colour." } },
  { id: "tin", licht: "/3d/driehoeksnet-licht.png", donker: "/3d/driehoeksnet-donker.png", cat: "terrein",
    nl: { titel: "Driehoeksnet (TIN)", tekst: "Het oppervlak waarop de machine stuurt." },
    fr: { titel: "Réseau de triangles (TIN)", tekst: "La surface sur laquelle la machine se guide." },
    en: { titel: "Triangle network (TIN)", tekst: "The surface the machine guides on." } },
  { id: "lijnwerk", ...r("p-betrix-draad"), cat: "terrein",
    nl: { titel: "Lijnwerk", tekst: "Breeklijnen en kanten als referentie voor de machinist." },
    fr: { titel: "Filaire", tekst: "Lignes de rupture et bords comme repères pour le conducteur." },
    en: { titel: "Linework", tekst: "Breaklines and edges as references for the operator." } },
];

// Uitgelicht: één model in vier weergaven.
export type Weergave = "hoogte" | "helling" | "hoogtelijn" | "draad";
export const WEERGAVEN: Record<Weergave, { nl: string; fr: string; en: string }> = {
  hoogte: { nl: "Hoogtekleuren", fr: "Couleurs hypsométriques", en: "Height colours" },
  helling: { nl: "Helling", fr: "Pente", en: "Slope" },
  hoogtelijn: { nl: "Hoogtelijnen", fr: "Courbes de niveau", en: "Contours" },
  draad: { nl: "Driehoeksnet", fr: "Réseau de triangles", en: "Triangle network" },
};

export const UITGELICHT: { id: string; nl: Tekst; fr: Tekst; en: Tekst }[] = [
  { id: "libramont",
    nl: { titel: "Platform met funderingsstroken", tekst: "Een groot werkvlak met een raster van funderingsstroken, elk op zijn eigen niveau. De hellingskaart toont meteen of elke strook correct afwatert." },
    fr: { titel: "Plateforme avec semelles", tekst: "Une grande plateforme avec une trame de semelles, chacune à son propre niveau. La carte des pentes montre aussitôt si chaque semelle s'écoule correctement." },
    en: { titel: "Platform with strip foundations", tekst: "A large working platform with a grid of strip foundations, each at its own level. The slope map shows straight away whether every strip drains correctly." } },
  { id: "riga",
    nl: { titel: "Uitgraving met taluds", tekst: "Een uitgraving met taluds rondom en een vlakke bodem. In het driehoeksnet ziet u hoe het oppervlak opgebouwd is waarop de machine stuurt." },
    fr: { titel: "Excavation talutée", tekst: "Une excavation avec talus périphériques et fond plat. Le réseau de triangles montre comment est construite la surface sur laquelle la machine se guide." },
    en: { titel: "Battered excavation", tekst: "An excavation with slopes all round and a level bottom. The triangle network shows how the surface the machine guides on is built." } },
];
