-- 0049 — Tickets compleet
--
-- Wat: soort (vraag/revisie/machine/afspraak/intern), project, taal,
-- machinesturing, volgnummer (#1001), wie aan zet is, gelezen-markering
-- (klant en studio), bijlagen, interne notities, revisie-uren en de koppeling
-- revisiefactuur <-> ticket (+ btw-verlegging per losse factuur).
--
-- Uitvoeren: Supabase -> SQL Editor -> plak dit volledige bestand -> Run.
-- Veilig om opnieuw te draaien (if not exists / drop ... if exists / DO-blokken).
--
-- VOLGORDE: eerst de nieuwe code deployen, DAN deze migratie draaien.
-- Ze neemt klanten het recht af om zelf (via de REST-API) tickets en
-- berichten in te voegen; dat doet voortaan de server (service-role) na een
-- eigendomscontrole. De nieuwe code werkt ook zonder deze migratie
-- (basisstand: geen bijlagen, notities, uren, projectkoppeling of 'ongelezen').

-- ---------- 1. Nieuwe kolommen op tickets ----------
alter table public.tickets
  add column if not exists soort              text not null default 'vraag',
  add column if not exists project_id         uuid references public.projecten (id) on delete set null,
  add column if not exists locale             text,
  add column if not exists systeem            text,
  add column if not exists wacht_op           text not null default 'studio',
  add column if not exists laatste_bericht_op timestamptz,
  add column if not exists laatste_afzender   text,
  add column if not exists laatste_fragment   text,
  add column if not exists klant_gelezen_op   timestamptz,
  add column if not exists studio_gelezen_op  timestamptz,
  add column if not exists eerste_antwoord_op timestamptz,
  add column if not exists gesloten_op        timestamptz,
  add column if not exists revisie_akkoord_op timestamptz,
  add column if not exists herinnerd_op       timestamptz;

-- Leesbaar volgnummer (#1001, #1002 ...). Bestaande rijen krijgen er meteen een.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'tickets' and column_name = 'nummer'
  ) then
    alter table public.tickets
      add column nummer bigint generated by default as identity (start with 1001);
    -- ADD COLUMN nummert in de volgorde op schijf (een bijgewerkt ticket staat
    -- achteraan); hernummer daarom op aanmaakdatum. Zelfde reeks 1001..1000+N,
    -- dus het volgende nieuwe ticket krijgt gewoon 1000+N+1.
    update public.tickets t
       set nummer = o.n
      from (
        select id, 1000 + row_number() over (order by created_at, id) as n
          from public.tickets
      ) o
     where o.id = t.id;
  end if;
end $$;
create unique index if not exists tickets_nummer_idx on public.tickets (nummer);

-- ---------- 2. Bestaande rijen bijwerken (enkel bij de EERSTE run) ----------
-- Herkenbaar aan het nog ontbreken van tickets.klant_ongelezen (stap 3).
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'tickets' and column_name = 'klant_ongelezen'
  ) then
    update public.tickets set status = 'open' where status = 'in_behandeling';
    update public.tickets set gesloten_op = updated_at
     where status = 'gesloten' and gesloten_op is null;

    update public.tickets set soort = 'revisie'
     where soort = 'vraag' and subject like 'Revisie — %';
    update public.tickets set soort = 'afspraak'
     where soort = 'vraag' and subject like '[Afspraak]%';
    update public.tickets set soort = 'intern'
     where soort = 'vraag' and lower(client_email) = 'info@studio-vm.be' and subject like '[%]%';

    update public.tickets t
       set project_id = p.id
      from public.projecten p
     where t.project_id is null
       and t.soort = 'revisie'
       and lower(p.client_email) = lower(t.client_email)
       and t.subject = left('Revisie — ' || p.titel, 160);

    update public.tickets t
       set laatste_bericht_op = m.created_at,
           laatste_afzender   = m.sender,
           laatste_fragment   = left(regexp_replace(m.body, '\s+', ' ', 'g'), 200),
           wacht_op           = case when m.sender = 'studio' then 'klant' else 'studio' end
      from (
        select distinct on (ticket_id) ticket_id, sender, body, created_at
          from public.ticket_messages
         order by ticket_id, created_at desc
      ) m
     where m.ticket_id = t.id
       and t.laatste_bericht_op is null;

    update public.tickets t
       set eerste_antwoord_op = f.eerste
      from (
        select ticket_id, min(created_at) as eerste
          from public.ticket_messages
         where sender = 'studio'
         group by ticket_id
      ) f
     where f.ticket_id = t.id
       and t.eerste_antwoord_op is null;

    -- Alles van voor deze migratie geldt als gelezen ('gelezen' bestond niet).
    update public.tickets
       set klant_gelezen_op  = coalesce(klant_gelezen_op, laatste_bericht_op),
           studio_gelezen_op = coalesce(studio_gelezen_op, laatste_bericht_op)
     where laatste_bericht_op is not null;
  end if;
end $$;

-- ---------- 3. 'Ongelezen'-vlaggen: altijd afgeleid, kunnen niet uit sync raken ----------
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'tickets' and column_name = 'klant_ongelezen'
  ) then
    alter table public.tickets add column klant_ongelezen boolean
      generated always as (
        coalesce(
          laatste_afzender = 'studio'
          and (klant_gelezen_op is null or klant_gelezen_op < laatste_bericht_op),
          false)
      ) stored;
  end if;
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'tickets' and column_name = 'studio_ongelezen'
  ) then
    alter table public.tickets add column studio_ongelezen boolean
      generated always as (
        coalesce(
          laatste_afzender = 'klant'
          and (studio_gelezen_op is null or studio_gelezen_op < laatste_bericht_op),
          false)
      ) stored;
  end if;
end $$;

-- ---------- 4. Controles ----------
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tickets_soort_chk') then
    alter table public.tickets add constraint tickets_soort_chk
      check (soort in ('vraag', 'revisie', 'machine', 'afspraak', 'intern'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tickets_wacht_op_chk') then
    alter table public.tickets add constraint tickets_wacht_op_chk
      check (wacht_op in ('studio', 'klant'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tickets_laatste_afzender_chk') then
    alter table public.tickets add constraint tickets_laatste_afzender_chk
      check (laatste_afzender is null or laatste_afzender in ('klant', 'studio'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tickets_locale_chk') then
    alter table public.tickets add constraint tickets_locale_chk
      check (locale is null or locale in ('nl', 'fr', 'en', 'de', 'es'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tickets_systeem_len_chk') then
    alter table public.tickets add constraint tickets_systeem_len_chk
      check (systeem is null or char_length(systeem) <= 80);
  end if;
  -- Lengtegrenzen: 'not valid' = enkel voor nieuwe/gewijzigde rijen.
  if not exists (select 1 from pg_constraint where conname = 'tickets_subject_len_chk') then
    -- Een 'not valid'-controle geldt wel bij elke UPDATE, en de trigger (stap 6)
    -- werkt het ticket bij elk bericht bij: maak bestaande onderwerpen eerst
    -- passend, anders kan zo'n oud ticket nooit meer beantwoord of gesloten worden.
    update public.tickets set subject = left(subject, 200) where char_length(subject) > 200;
    update public.tickets set subject = '—' where char_length(subject) = 0;
    alter table public.tickets add constraint tickets_subject_len_chk
      check (char_length(subject) between 1 and 200) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'ticket_messages_body_len_chk') then
    alter table public.ticket_messages add constraint ticket_messages_body_len_chk
      check (char_length(body) between 1 and 10000) not valid;
  end if;
end $$;

-- ---------- 5. Indexen ----------
create index if not exists tickets_project_idx
  on public.tickets (project_id) where project_id is not null;
create index if not exists tickets_email_lower_idx
  on public.tickets (lower(client_email));
create index if not exists tickets_werklijst_idx
  on public.tickets (status, wacht_op, laatste_bericht_op);
create index if not exists ticket_msg_ticket_tijd_idx
  on public.ticket_messages (ticket_id, created_at desc);

-- ---------- 6. Trigger: elk nieuw bericht werkt het ticket bij ----------
create or replace function public.ticket_na_bericht()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.tickets
     set laatste_bericht_op = new.created_at,
         laatste_afzender   = new.sender,
         laatste_fragment   = left(regexp_replace(new.body, '\s+', ' ', 'g'), 200),
         wacht_op           = case when new.sender = 'studio' then 'klant' else 'studio' end,
         eerste_antwoord_op = case when new.sender = 'studio'
                                   then coalesce(eerste_antwoord_op, new.created_at)
                                   else eerste_antwoord_op end,
         klant_gelezen_op   = case when new.sender = 'klant'
                                   then greatest(coalesce(klant_gelezen_op, new.created_at), new.created_at)
                                   else klant_gelezen_op end,
         studio_gelezen_op  = case when new.sender = 'studio'
                                   then greatest(coalesce(studio_gelezen_op, new.created_at), new.created_at)
                                   else studio_gelezen_op end,
         herinnerd_op       = null,
         updated_at         = now()
   where id = new.ticket_id;
  return new;
end;
$$;

drop trigger if exists ticket_na_bericht on public.ticket_messages;
create trigger ticket_na_bericht
  after insert on public.ticket_messages
  for each row execute function public.ticket_na_bericht();

-- ---------- 7. Bijlagen, interne notities, revisie-uren ----------
create table if not exists public.ticket_bijlagen (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  ticket_id   uuid not null references public.tickets (id) on delete cascade,
  message_id  uuid references public.ticket_messages (id) on delete set null,
  door        text not null check (door in ('klant', 'studio')),
  naam        text not null check (char_length(naam) between 1 and 200),
  pad         text not null unique,
  grootte     bigint,
  mime        text
);
create index if not exists ticket_bijlagen_ticket_idx on public.ticket_bijlagen (ticket_id);

-- Interne notities: NOOIT zichtbaar voor de klant (geen policies).
create table if not exists public.ticket_notities (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  ticket_id   uuid not null references public.tickets (id) on delete cascade,
  body        text not null check (char_length(body) between 1 and 10000)
);
create index if not exists ticket_notities_ticket_idx on public.ticket_notities (ticket_id, created_at);

-- Revisie-uren per ticket; tarief = momentopname van de projectcategorie.
create table if not exists public.ticket_uren (
  id               uuid primary key default gen_random_uuid(),
  created_at       timestamptz not null default now(),
  ticket_id        uuid not null references public.tickets (id) on delete cascade,
  project_id       uuid references public.projecten (id) on delete set null,
  uren             numeric(6, 2) not null check (uren > 0 and uren <= 999),
  tarief_cent      integer not null check (tarief_cent >= 0),
  omschrijving     text check (omschrijving is null or char_length(omschrijving) <= 300),
  invoice_id       uuid references public.invoices (id) on delete set null,
  naar_project_op  timestamptz
);
create index if not exists ticket_uren_ticket_idx on public.ticket_uren (ticket_id);
create index if not exists ticket_uren_open_idx
  on public.ticket_uren (project_id) where invoice_id is null and naar_project_op is null;

-- ---------- 8. Facturen: revisiefactuur <-> ticket, btw-verlegging per factuur ----------
alter table public.invoices
  add column if not exists ticket_id   uuid references public.tickets (id) on delete set null,
  add column if not exists vat_reverse boolean;
create index if not exists invoices_ticket_idx
  on public.invoices (ticket_id) where ticket_id is not null;

-- ---------- 9. Rechten (RLS) ----------
-- Lezen: klant ziet enkel zijn eigen tickets/berichten/bijlagen (hoofdletterongevoelig).
drop policy if exists tickets_own on public.tickets;
create policy tickets_own on public.tickets
  for select to authenticated
  using (lower(client_email) = public.current_email());

drop policy if exists tmsg_own on public.ticket_messages;
create policy tmsg_own on public.ticket_messages
  for select to authenticated
  using (
    exists (
      select 1 from public.tickets t
       where t.id = ticket_messages.ticket_id
         and lower(t.client_email) = public.current_email()
    )
  );

alter table public.ticket_bijlagen enable row level security;
alter table public.ticket_notities enable row level security;
alter table public.ticket_uren     enable row level security;

drop policy if exists tbijl_own on public.ticket_bijlagen;
create policy tbijl_own on public.ticket_bijlagen
  for select to authenticated
  using (
    exists (
      select 1 from public.tickets t
       where t.id = ticket_bijlagen.ticket_id
         and lower(t.client_email) = public.current_email()
    )
  );
-- ticket_notities en ticket_uren: bewust GEEN policies -> enkel de service-role.

-- Schrijven: enkel nog de server (service-role) na eigendomscontrole.
-- 'revoke all' (ook truncate/references/trigger, waar RLS niet voor geldt),
-- daarna enkel lezen terug voor aangemelde klanten (de policies hierboven).
drop policy if exists tickets_create on public.tickets;
drop policy if exists tmsg_create on public.ticket_messages;
revoke all on public.tickets, public.ticket_messages, public.ticket_bijlagen from anon, authenticated;
grant select on public.tickets, public.ticket_messages, public.ticket_bijlagen to authenticated;
revoke all on public.ticket_notities from anon, authenticated;
revoke all on public.ticket_uren     from anon, authenticated;

-- ---------- 10. Prive-opslag voor bijlagen (max. 50 MB per bestand) ----------
-- Geen storage-policies: opladen via eenmalige upload-links, downloaden via
-- tijdelijke links die de server pas na een eigendomscontrole aanmaakt.
insert into storage.buckets (id, name, public, file_size_limit)
values ('ticket-bijlagen', 'ticket-bijlagen', false, 52428800)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit;

notify pgrst, 'reload schema';
